# @name chaining
GET http://localhost:7071/api/HttpTriggerChaining

###
@instanceId = {{chaining.response.body.$.id}}
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{instanceId}}
    ?taskHub=DemoDurableTaskAnalyzerV1
    &connection=Storage
    &code=KktzPVrv2dvw24NpPH1iBFbp/riVYaRiIuZ/DkW/XFXPwCDXbTpxtg==